spring.application.name=mgm-backend

# --- Database Internet ---
spring.datasource.internet.jdbc-url=jdbc:h2:mem:internet_db;DB_CLOSE_DELAY=-1
spring.datasource.internet.username=sa
spring.datasource.internet.password=
spring.datasource.internet.driver-class-name=org.h2.Driver

# --- Database Intranet ---
spring.datasource.intranet.jdbc-url=jdbc:h2:mem:intranet_db;DB_CLOSE_DELAY=-1
spring.datasource.intranet.username=sa
spring.datasource.intranet.password=
spring.datasource.intranet.driver-class-name=org.h2.Driver

# --- JPA & H2 Console ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true

# Aktifkan Penjadwalan
spring.main.allow-bean-definition-overriding=true